### ISSUE TITLE
TypeError: cannot pickle '_thread.lock' object

### ISSUE THREAD

**Issue by ruevaughn** [bahruzjabiyev/T-Reqs-HTTP-Fuzzer#1]
Hi, i'm getting this error when I try to run with the following command: `python   main.py -c ../config -i -s 505`

```
Traceback (most recent call last):
  File "/Users/cjensen/projects/T-Reqs-HTTP-Fuzzer/code/main.py", line 165, in <module>
    fuzzer.blackbox_fuzz_individual(fuzzer.seedfile, [fuzzer.seed])
  File "/Users/cjensen/projects/T-Reqs-HTTP-Fuzzer/code/main.py", line 117, in blackbox_fuzz_individual
    proc.start()
  File "/Users/cjensen/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/cjensen/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/cjensen/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/cjensen/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/cjensen/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/cjensen/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/cjensen/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object
```

Any idea what I can do?

**Comment by ertygiq** [comment]
This is due to `self.lock = threading.Lock()` instance variable.
Move the lock out of the class (e.g., to global variable) and the code will work with the latest python version.

**Comment by An-Bin** [comment]
> 这是由于`self.lock = threading.Lock()`实例变量造成的。 将锁移出类（例如移至全局变量），代码将适用于最新的 Python 版本。

你好，在Python3.7中也遇到了类似的问题，应该怎么操作呢？能具体的说一下步骤吗，谢谢！
Namespace(config='../config', individual_mode=False, no_sending=False, outfilename=None, seed=None, seedfile=None, verbose=False)
Traceback (most recent call last):
  File "main.py", line 186, in <module>
    fuzzer.blackbox_fuzz_parallel_batch()
  File "main.py", line 105, in blackbox_fuzz_parallel_batch
    proc.start()
  File "D:\SoftWare\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\SoftWare\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\SoftWare\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\SoftWare\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\SoftWare\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects
